- name: Add a setting to ~/.gitconfig
  become: true
  become_user: "{{current_user}}"
  community.general.git_config:
    name: "{{item.name}}"
    scope: global
    value: "{{item.value}}"
  loop:
    - { name: 'user.email'          , value: '{{current_user}}@{{current_user}}' } 
    - { name: 'user.name'           , value: '{{current_user}}' } 
    - { name: 'core.editor'         , value: 'vim' } 
    - { name: 'alias.tree'          , value: "log --graph --all --decorate --source --name-only" }
    - { name: 'alias.lg'            , value: "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit" } 
    - { name: 'alias.ignore'        , value: '! git update-index --assume-unchanged' }
    - { name: 'alias.unignore'      , value: '! git update-index --no-assume-unchanged' }
    - { name: 'alias.ignored'       , value: '! git ls-files -v | grep ^[a-z]' }
    - { name: 'alias.auto-mr'       , value: '! git commit --allow-empty -m "AUTO-MR"' }
    - { name: 'alias.clone-branches', value: '! git branch -a | sed -n "/\/HEAD /d; /\/master$/d; /remotes/p;" | xargs -L1 git checkout -t' }
    - { name: 'alias.analises'      , value: '! git add . && git commit --allow-empty -m "Analises ..." && git push' }
    
#########################################################################################
# - name: CONFS ROOT
#   lineinfile:
#     path: "{{item.path}}"
#     regexp: "{{item.regexp}}"
#     line: "{{item.line}}"
#   loop:
#     - { path: '/etc/default/tor', regexp: 'RUN_DAEMON="yes"', line: 'RUN_DAEMON="no"' }
#########################################################################################
- name: VSCODE {{current_user}}
  shell: "code --install-extension {{item}}"
  become: true
  become_user: "{{current_user}}"
  loop:
    - alexkrechik.cucumberautocomplete
    - vscoss.vscode-ansible
    - ms-azuretools.vscode-docker
    - editorconfig.editorconfig
    - eamodio.gitlens
    - shd101wyy.markdown-preview-enhanced 
    - ryu1kn.partial-diff
    - felixfbecker.php-debug
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client
    - ecodes.vscode-phpmd
    - breezelin.phpstan
    - ikappas.phpcs
    - kokororin.vscode-phpfmt
#########################################################################################
- name: SHORTCUTS {{current_user}}
  become: true
  become_user: "{{current_user}}"
  xfconf:
    channel: xfce4-keyboard-shortcuts
    property: "{{item.property}}"
    value_type: string
    value: "{{item.value}}"
  loop:
    - { property: '/commands/custom/<Super>e' , value: 'thunar' } 
    - { property: '/commands/custom/<Super>l' , value: 'xflock4' } 
    - { property: '/xfwm4/custom/<Super>d'    , value: 'show_desktop_key' } 
    
#########################################################################################
# Files
- name: AVATAR > Copy
  copy: src=roles/{{flavor}}/files/avatar.jpg dest=/home/{{current_user}}/.face owner={{current_user}} group={{current_user}} mode=600

- name: VSCODE > Settings
  become: true
  become_user: "{{current_user}}"
  copy: src=roles/{{flavor}}/files/settings.json dest=/home/{{current_user}}/.config/Code/User/settings.json
#########################################################################################
# - name: Geral
#   shell: "{{item}}"
#   with_items:
#      - "rm /etc/apt/sources.list.d/google-chrome-stable.list"
#########################################################################################

