#########################################################################################
- name: Repository > Cryptomator | multi-platform client-side encryption of your cloud files 
  apt_repository:
    repo: ppa:sebastian-stenzel/cryptomator
    state: present
    update_cache: no
    filename: cryptomator
#########################################################################################
# - name: APT_KEY > Google Chrome
#   apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub

# - name: Repository > Google Chrome
#   apt_repository:
#     repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
#     update_cache: no
#     state: present
#     filename: google-chrome
#########################################################################################
- name: Repository > OBS-STUDIO
  apt_repository:
    repo: ppa:obsproject/obs-studio
    update_cache: no
    state: present
    filename: obs-studio
#########################################################################################
# - name: Repository > Vidcutter | the simplest + fastest video cutter & joiner 
#   apt_repository:
#     repo: ppa:ozmartian/apps
#     update_cache: no
#     state: present
#     filename: vidcutter
#########################################################################################
# - name: Repository > Kdenlive
#   apt_repository:
#     repo: ppa:kdenlive/kdenlive-stable
#     update_cache: no
#     state: present
#     filename: kdenlive
#########################################################################################
